### ISSUE TITLE
Internal Server Error 

### ISSUE THREAD

**Issue by parsap** [dgreif/homebridge-hatch-baby-rest#107]
My plugin is on a loop of 500 server errors when it tries to log in.  Is this happening to anyone else?  The native app still works.

  body: {
    timestamp: '2023-06-06 21:31:03.254',
    status: 500,
    error: 'Internal Server Error',
    path: '/public/v1/login'
  },

Here is the full log.

[log.txt](https://github.com/dgreif/homebridge-hatch-baby-rest/files/11669561/log.txt)

**Comment by joshuaseltzer** [comment]
Same error on my instance. Looks like the OAuth flow is failing. Guessing their API is either down or it changed...

**Comment by brentleeper** [comment]
Looks like the following header needs to be added to each request.

USER_AGENT: "hatch_rest_api"

**Comment by brentleeper** [comment]
… well actually… let me try to understand this a bit more

**Comment by brentleeper** [comment]
Yes, that is correct. All api requests now require the above mentioned header, including the login request.

**Comment by joshuaseltzer** [comment]
@brentleeper nice discovery! Hopefully the fix is just as simple as adding that header to the requests made by this plugin.

I'd do a PR myself, but I'm not at all familiar with developing these plugins or even the language used here.

**Comment by brentleeper** [comment]
I am on my phone currently but I just opened a PR to address this issue. It should be noted I have very little context 😅 and working off some assumptions but the maintainer should get the idea and be able to edit as needed.

**Comment by brentleeper** [comment]
Opened PR: https://github.com/dgreif/homebridge-hatch-baby-rest/pull/108

**Comment by dgreif** [comment]
The fix from #108 has been released in `4.0.1`. Please let me know if this resolves your issues @parsap

**Comment by eightball011854** [comment]
@dgreif major thanks for this and the ring fix last weekend - you are the best of the best of the best!

**Comment by joshuaseltzer** [comment]
> The fix from #108 has been released in `4.0.1`. Please let me know if this resolves your issues @parsap 

I can personally confirm 4.0.1 is working again on my install.

Thanks again for quickly publishing this update! Couldn't live without it.

**Comment by parsap** [comment]
Confirmed fixed!

**Comment by kenwdelong** [comment]
So just to be clear - the 500s were due to a bug on our end; now fixed.  The user-agent is a bit of a red herring: it could have been set to "bobs-your-uncle" and that would have avoided the bug.

The bug manifested because we are implementing some rate-limiting.  Someone mentioned being in a infinite loop of 500s - there are quite a few people using this library in an infinite loop of 200s (successful logins).  There are clients out there sending tens of thousands of login attempts per day. This is one of the things that prompted us to implement rate limiting!

We meant to look over the project and submit some pull requests to fix the infinite-login-loop problem, but we just haven't had the time.  It would be great if someone could figure it out.  The login tokens are valid for years.  But be aware that as soon as we get this code spruced up the infinite login loops will be getting 429 responses, regardless of user-agent.

**Comment by dgreif** [comment]
Thanks for the heads up @kenwdelong, and sorry for the infinite loop login attempts! I didn't realize that was happening and haven't seen anything like that on my end, but I would gladly accept some PRs if you find the offending code.
