### ISSUE TITLE
Use Lightbulb instead of speaker to allow Homekit control

### ISSUE THREAD

**Issue by reidwilbur** [dgreif/homebridge-hatch-baby-rest#111]
As far as I can find so far, homekit does not allow controlling the volume of speakers.

https://github.com/dgreif/homebridge-hatch-baby-rest/blob/4d1b78472343154b345f5f130ca5362e07e01231/packages/shared/sound-machine.ts#L24

The above shows up as a speaker in my Homebridge and is controllable via the HB UI, but doesn't show up in Homekit nor is it controllable.

In other projects, I have seen people use a Lightbulb service as a workaround to enable controlling the volume of a speaker device in automations.  Would that be possible to implement here? Or have it as a configurable option?

I've been trying to change it in my local copy to see if I can get it working, but not having much luck so far.

**Comment by dgreif** [comment]
Thanks for the idea @reidwilbur! I too have seen similar setups and have been forced to use different service types to get devices exposed properly in HomeKit. The Speaker service is very unfortunate because it is technically a real service, but the Home app doesn't directly support it. There are other HomeKit apps out there (can't remember which off hand) which _do_ support Speakers for simple volume controls.

Given that we are technically doing things correctly right now, but Apple is falling short on support, I'd prefer not to make any changes. This would be good feedback for Apple and the Home app, but I'd prefer not to add more complication/config to get this working in this homebridge plugin
