### ISSUE TITLE
Rest+ Homekit Display

### ISSUE THREAD

**Issue by 23maverick23** [dgreif/homebridge-hatch-baby-rest#112]
I'm not sure if this is misconfiguration, or a bug. I was able to easily setup my Rest+ Gen 1, however I'm seeing a discrepancy between Homebridge and the Home app.

Inside Homebridge, I see 4 "Accessories" for the Rest+ (a switch, a light, a fan, and a speaker). Based on the documentation, and some playing around, these are the ways you can control things like light color, which track is playing, and the volume of the track.

However, inside the Home app, only 3 of those transfer (a switch, a light, a fan) which leaves me with not being able to control the volume of the Rest+ as I change settings via Home or Shortcuts.

Anything I may have missed in the setup, or is this just a current limitation in the config? Would love to be able to mimic Rest Scenes using Apple Shortcuts, but I need the Speaker/Volume control available to do that. Thx.

**Comment by dgreif** [comment]
Unfortunately this is a missing feature on the Home/Apple side. HomeKit has support for "speakers", but the Home app itself does not. Hopefully one day they will add better support, but there isn't much we can do from the homebridge side. You can look into 3rd party HomeKit apps, some of which have speaker support (I think Eve does, not positive). There are some hacky workarounds I _could_ do from the plugin, like exposing a dimmer switch instead of a speaker, but ultimately it's on Apple to fully support their own protocol 😅
