### ISSUE TITLE
Failed to reach server error

### ISSUE THREAD

**Issue by JeffJeanBap** [dgreif/homebridge-hatch-baby-rest#135]
I'm getting the following error on the HOOBS plugin. This seems to work fine on homebridge using the same exact config. 

**

> Hatch Baby Rest BridgeHatchBabyRestERRORFailed to reach Hatch Baby server at https://prod-sleep.hatchbaby.com/public/v1/login.  fetch is not defined.  Trying again in 5 seconds...

**

![CleanShot 2024-07-26 at 17 29 38@2x](https://github.com/user-attachments/assets/6ec1eb29-d7e4-43e4-a28b-cb877cd04b98)

**Comment by Homekitdude** [comment]
Any hope for a fix?!

**Comment by Homekitdude** [comment]
@dgreif any hope for a fix?

**Comment by jonarogers** [comment]
I am having this server issue as well.

**Comment by Homekitdude** [comment]
Looks like the developer abandoned this plugin.

**Comment by tsightler** [comment]
Not abandoned, actually, the release notes clearly state that NodeJS v18 or needed is required for the 5.x versions of this plugin.  The error above is caused by using an unsupported, end-of-life NodeJS version.  Use modern Homebridge with a supported NodeJS version and the plugin will work.  You should contact HOOBS for any assistance upgrading to a supported NodeJS version, assuming they are still responding to support requests.

**Comment by JeffJeanBap** [comment]
Thanks @tsightler my node version is updated and seems to be running now. 

Your contribution to this plugin is very much appreciated @dgreif !
