### ISSUE TITLE
Hatch Restore Support or extension?

### ISSUE THREAD

**Issue by craldaz** [dgreif/homebridge-hatch-baby-rest#32]
Is it possible to extend this plugin to work with the hatch restore?

**Comment by dgreif** [comment]
It's definitely possible, but I don't own one so I can't test with it to see how it works. I honestly have been wondering if it would just work like the rest plus, and this is the first request I have had that suggests otherwise. If you are a developer, I'd be happy to take a pull request.

**Comment by craldaz** [comment]
I am definitely not a developer maybe you could say very amateur DIYer, in any case I have the Hatch Rest and Homebridge configured with the raspberry pi and homekit

In homekit it is saying "No Response" 

It also caused my homekit and raspberry pi to become completely unresponsive and I had to reinstall my image, not sure if this is related.

But if you have any recommendations I'd be willing to try it out again.

**Comment by dgreif** [comment]
@craldaz could you provide any additional info on what you see when you set up the plugin with your Restore light?  does the Restore show up in HomeKit but not respond, or do you only see your Rest? Does the Rest light still work? If the Restore is breaking the plugin when included, I'd definitely like to at least prevent that from happening.

**Comment by dgreif** [comment]
@craldaz I just released v`2.1.0` which should prevent the Restore light from showing up and breaking homebridge. When you start the plugin, you may see a log that says something like `Unsupported Light Found: ....`.  If you could post the contents of that line here, that may be helpful in adding actual support for the Restore.  I will probably need more info after that, but it's a start.

**Comment by ajf102** [comment]
I’m going to tinker with this plugin since I have a restore. What information would be useful for you to get it working?

**Comment by craldaz** [comment]
I can test it too if anyone gets something going

**Comment by dgreif** [comment]
Hey everyone, I appreciate the enthusiasm! I am receiving the new Rest Mini on Wednesday and will see how it compares to the Rest. That should hopefully give me an idea of how hatch is doing things on different lights, which may give me insight into how they did the restore. In the end, though, it may be easiest to have someone share their login so that I can interact with the restore directly and take a look at how the data is structured. I'll follow up after I get a chance to play around with the mini

**Comment by WinterC15** [comment]
Any update on the Restore compatibility? Thanks for all of your work in this plugin!

**Comment by dgreif** [comment]
No updates yet.  Out of curiosity, what are the main things you would like to control on the Restore? I don't own one, but it Sunrise Alarm and a large library of sounds/stories.  Do you mainly want to control the light/color, or sounds and other features too?

**Comment by WinterC15** [comment]
Thanks for the reply. For my everyday use, I have deleted/disabled all of the stations except for the sleep station. I would primarily just like to be able to turn the Restore on and  off with my respective good night and good morning scenes within HomeKit. I would use it in an identical manner as the Hatch Rests. I hope that helps as I know the Restore has a much larger library of tracks and light settings.

**Comment by dgreif** [comment]
Alright, I finally broke down and bought a Restore because I wanted to make the plugin feature complete 😅.  Just released v`3.2.0` with Restore support.  Here's an excerpt from the Readme explaining some limitations:

> The Hatch Restore supports much more complicated routines that do not map well to HomeKit controls.  Because of this complexity, the Restore is exposed as a simple switch.  Turning the switch on will initiate the first step in your Bedtime routine.  Turning the switch off will turn the device off no matter which routine/step you are in.

Hopefully this switch approach gives you the functionality you need without being crazy complicated in implementation.  Let me know how it works for you all!
