### ISSUE TITLE
homebridge/Home do not reflect manual device adjustments

### ISSUE THREAD

**Issue by timwitty** [dgreif/homebridge-hatch-baby-rest#44]
I've updated to 3.0 to get the ability to use as a wake light.

I did have one question though. Is it expected that the Home app or homebridge will sync its config with the actual state of the device at any point? I've configured the device with the plugin, then turned it to a favorite via the ring as I put my child in the crib but Home/homebridge still shows what I had set it to prior. I'm not sure if this is expected or not. The behavior is correct with regard to the plugin and homebridge not overriding my manual adjustment.

If not expected would it be possible to have this feature,  configurable setting for how often it should sync?

Device: bluetooth

**Comment by dgreif** [comment]
With the bluetooth lights, state is only synced while the device is connected.  The plugin will only connect for a short period of time when you make changes on the HomeKit side because if you are connected from homebridge, then you cannot connect from the Hatch app.   The plugin _could_ periodically connect, but you wouldn't know if HomeKit was always up to date or not.  I'm not sure there is a great solution for this in the near future, so I'm going to close this for now
